[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

