[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/models/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=2592000"

[[headers]]
  for = "/hdr/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=2592000"

